### PR TITLE
#120 Adds admin login DB, minor bug fixes

### LINKED ISSUE #120: Sync admin password with database
References #39 

Requires an admin ID and unique password to log in

### PR DESCRIPTION
**Pull request by AdamM-1021**
Closes #120

### CODE REVIEW

**Review by TedMoore1 — APPROVED** [review]
Looks great

File: eis-tracker/app/api/login/route.ts [hunk 1]
```diff
@@ -1,11 +1,21 @@
...
+
+    const record = db.prepare("SELECT Password FROM passwords WHERE ID = ?").get(id);
+
+    if (!record) {
+        return NextResponse.json({ message: "User not found" }, { status: 401 });
+    }
+
     // Simple authentication check (Replace with real logic)
-    if (id === "999999999" && pass === "admin123") {
+    // @ts-ignore
```
Comment (TedMoore1) [inline eis-tracker/app/api/login/route.ts:17]:
```suggestion
    // @ts-expect-error
```
